# Generated by Django 3.1.7 on 2021-06-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20210611_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=8, unique=True)),
                ('room_type', models.CharField(choices=[('LAB', 'Lab'), ('THEORY', 'Theory')], max_length=6, verbose_name='Room Type')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FREE', 'FREE'), ('ENG', 'ENGAGED')], max_length=4, verbose_name='Engagement Status')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.timetable')),
            ],
            options={
                'unique_together': {('room', 'time_table')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='time_table',
            field=models.ManyToManyField(blank=True, through='core.RoomEngagement', to='accounts.TimeTable'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=60, verbose_name='Course Name')),
                ('course_code', models.CharField(max_length=10, verbose_name='Course Code')),
                ('course_type', models.CharField(choices=[('LAB', 'Lab'), ('THEORY', 'Theory')], max_length=6, verbose_name='Course Type')),
                ('course_credit', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Course Credit')),
                ('preference', models.CharField(choices=[('MAJOR', 'Major'), ('MINOR', 'Non-Major')], max_length=5, verbose_name='Department Preference')),
                ('semester', models.CharField(choices=[('11', '1/1'), ('12', '1/2'), ('21', '2/1'), ('22', '2/2'), ('31', '3/1'), ('32', '3/2'), ('41', '4/1'), ('42', '4/2')], max_length=2, verbose_name='Semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('11', '1/1'), ('12', '1/2'), ('21', '2/1'), ('22', '2/2'), ('31', '3/1'), ('32', '3/2'), ('41', '4/1'), ('42', '4/2')], max_length=2, verbose_name='Semester')),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednessday'), ('THU', 'Thursday')], max_length=3, verbose_name='day of the week')),
                ('time', models.CharField(max_length=5, verbose_name='time of the day')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('POSTPOND', 'Postpond')], max_length=9)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
    ]
