# Generated by Django 3.1.7 on 2021-06-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('POSTPOND', 'Postpond')], default='SCHEDULED', max_length=9),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab')], max_length=6, verbose_name='Course Type'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab')], max_length=6, verbose_name='Room Type'),
        ),
    ]
