# Generated by Django 3.1.7 on 2021-06-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacher_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='time_table',
            field=models.ManyToManyField(blank=True, through='accounts.Engagement', to='accounts.TimeTable'),
        ),
    ]
